### ISSUE TITLE
Add kleung@ as a reviewer on sigstore/helm-charts

### ISSUE THREAD

**Issue by k4leung4** [sigstore/helm-charts#132]
**Description**

I'm making a bunch of minor changes to the helm charts and would like to be able to more easily bunch versions of the helm charts to pick up new dependent chart versions.
Would be nice to have permissions to assign reviewers and merge permissions.

@dlorenc @cpanato

**Comment by sabre1041** [comment]
With the amount of great contribution that @k4leung4 has put forth, i'm totally in favor!

**Comment by dlorenc** [comment]
Cool, me too! I'll close this out.

**Comment by cpanato** [comment]
+1000

**Comment by hectorj2f** [comment]
👏🏻
