### ISSUE TITLE
What does error is pod policy-controller-policy-webhook means ?

### ISSUE THREAD

**Issue by MageshSrinivasulu** [sigstore/helm-charts#218]
{"level":"error","ts":"2022-06-17T10:44:39.559Z","logger":"clusterimagepolicy.ConversionWebhook","caller":"controller/controller.go:566","msg":"Reconcile error","knative.dev/traceid":"65c9274c-9590-4148-a43d-f106ec0dbd37","knative.dev/key":"clusterimagepolicies.policy.sigstore.dev","duration":0.000220403,"error":"custom resource \"clusterimagepolicies.policy.sigstore.dev\" isn't configured for webhook conversion","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20220325200448-1f7514acd0c2/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220325200448-1f7514acd0c2/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220325200448-1f7514acd0c2/controller/controller.go:491"}

**Comment by hectorj2f** [comment]
@MageshSrinivasulu could you specify the used chart version? You shouldn’t see this error anymore.

**Comment by MageshSrinivasulu** [comment]
@hectorj2f I am using the latest chart in this location https://github.com/sigstore/helm-charts/tree/main/charts/policy-controller
