### ISSUE TITLE
Is it possible to have the cosign running in non-blocking mode ? Like just logging stating that image is not signed without force blocking

### ISSUE THREAD

**Issue by MageshSrinivasulu** [sigstore/helm-charts#227]
I am asking this because. We are trying to apply cosign to our enterprise application. Where there is a lot of namespaces and each namespace has a dozen apps running in them. So even if one app in the namespace has non singed image it will block the working of the apps. Will there be any feature to run cosign in passive mode, just logging issue without actively blocking it? So that we can slowly enable to active mode when we are ready

**Comment by hectorj2f** [comment]
This issue looks related to this one https://github.com/sigstore/cosign/issues/1653. We'll have to work on that solution.
Feel to share your thoughts on the original issue.

**Comment by MageshSrinivasulu** [comment]
@hectorj2f. Is there any ETA for when this feature will be available?

**Comment by hectorj2f** [comment]
@MageshSrinivasulu it is possible to run the policy-controller in a non-blocking mode using https://github.com/sigstore/policy-controller/pull/69

**Comment by flxw** [comment]
Can we close this issue? It seems more related to product functionality than to the helm charts

**Comment by hectorj2f** [comment]
This has been done! Closing this issue.
