### ISSUE TITLE
Helm installation issue

### ISSUE THREAD

**Issue by blackcat-lin** [sigstore/helm-charts#24]
**Description**
I follow the instruction on https://github.com/sigstore/helm-charts/tree/main/charts/cosigned to install cosigned admission webhook in eks cluster, got below error when I run "helm install cosigned -n cosign-system sigstore/cosigned --devel --set webhook.secretKeyRef.name=mysecret".

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in Secret.data.cosign.key, unknown object type "nil" in Secret.data.cosign.password, unknown object type "nil" in Secret.data.cosign.pub]

And it works after pass below parameters value in the above command line:

--set cosign.cosignKey=‘base64 encode’ --set cosign.cosignPassword='base64 encode' --set cosign.cosignPub='base64 encode'

**Comment by adubey8** [comment]
I also encounter this issue. Please bump up the priority. Thanks!

**Comment by cpanato** [comment]
@blackcat-lin i think this was fixed in https://github.com/sigstore/helm-charts/pull/40

can you try it out?

**Comment by adubey8** [comment]
I encountered this problem 2 weeks ago. I looked at the code, and there was a change 9 days ago about the secretKeyRef. Now it should work. Thanks!

**Comment by cpanato** [comment]
@blackcat-lin i will close this issue, but feel free to reopen or open a new one if you still face the issue
