### ISSUE TITLE
When does the policy-controller's "configuring static authorities" feature take effect?

### ISSUE THREAD

**Issue by derekcha** [sigstore/helm-charts#242]
**Question**

hi. :) 
I checked the Configuring static authorities function in the sigstore [documentation](https://docs.sigstore.dev/policy-controller/overview/#configuring-static-authorities), and I confirmed that the function is also included in the code of policy-controller.
This is a feature I really need.
However, it seems that this function is not reflected in this helm-charts yet.
When will this feature be reflected?

I hope that will be reflected soon.
thank you !!

**Comment by hectorj2f** [comment]
@derekcha We'll release a new version shortly, then we will apply those changes to the helm-chart.

**Comment by derekcha** [comment]
@hectorj2f Thanks for the reply. I hope to apply soon.

**Comment by hectorj2f** [comment]
@derekcha we have released a new version of the policy-controller

**Comment by derekcha** [comment]
@hectorj2f 
I checked it. thank you so much!!
