### ISSUE TITLE
add ability to specify `rekor_server.hostname` for Rekor instance

### ISSUE THREAD

**Issue by bobcallaway** [sigstore/helm-charts#244]
Without the ability to set this field, the default value for this command line flag `rekor.sigstore.dev` gets returned in the signed log info checkpoints. 

@sabre1041 any guidance on where to add this?

**Comment by tylerauerbeck** [comment]
@bobcallaway Not sure if this is still relevant, but I believe this should be configurable via .Values.server.extraArgs?

**Comment by tylerauerbeck** [comment]
For other folks reference: https://github.com/sigstore/helm-charts/blob/main/charts/rekor/values.yaml#L136

Something like:

```
extraArgs:
  - rekor_server.hostname=rekor.myhost.io
```

**Comment by bobcallaway** [comment]
yup, that's how i ended up resolving it. thanks for pointing it out!
