### ISSUE TITLE
policy-controller Validation bypass was performed for all patterns, but validation failed occurred.

### ISSUE THREAD

**Issue by derekcha** [sigstore/helm-charts#275]
Hello.

**Description**
I set it to pass without validation check for all image patterns, but it was not distributed due to validation failed.

This is the ClusterImagePolicy I used.

> apiVersion: policy.sigstore.dev/v1beta1
> kind: ClusterImagePolicy
> metadata:
>   name: image-policy-default
> spec:
>   images:
>     - glob: "**"
>   authorities:
>     - static:
>         action: pass

The image I want to deploy.

>     spec:
>       - name: mysql
>         image: mysql:latest
>         imagePullPolicy: Always

Error message.
`Error from server (BadRequest): error when creating "test.yaml": admission webhook "policy.sigstore.dev" denied the request: validation failed: invalid value: mysql:latest must be an image digest: spec.template.spec.containers[0].image
`
Can you tell me why this error occurs?

**Version**
policy-controller version: 0.2.1

**Comment by sabre1041** [comment]
@derekcha This issue is better suited on the [policy-controller](https://github.com/sigstore/policy-controller) repository, but looking at the code [here](https://github.com/sigstore/policy-controller/blob/main/pkg/webhook/validator.go#L199), all containers must make use of digest references instead of named tags

**Comment by hectorj2f** [comment]
@derekcha The error comes from https://github.com/sigstore/policy-controller/blob/main/pkg/webhook/validator.go#L199. The policy-controller requires a digest, otherwise the validation is meaningless since the tag can move.

**Comment by sabre1041** [comment]
Closing as the issue was related to the specific features provided by the policy-controller itself and not the chart
