### ISSUE TITLE
cosigned: chart doesn't accept empty key password

### ISSUE THREAD

**Issue by ahmetb** [sigstore/helm-charts#28]
My key is passwordless (as cosign lets me create as such).

But helm chart doesn't accept that.
If I drop cosign.password field or set it to empty string, it still fails.

![image](https://user-images.githubusercontent.com/159209/139312289-99aade51-7f2f-4054-a838-a1fef9d5b9a6.png)

> helm install cosigned -n cosign-system sigstore/cosigned --devel --set webhook.secretKeyRef.name=mysecret
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in Secret.data.cosign.key, unknown object type "nil" in Secret.data.cosign.password, unknown object type "nil" in Secret.data.cosign.pub]

**Comment by hectorj2f** [comment]
@ahmetb It should work now, as fixed in #33. Please, feel free to re-open the issue.
