### ISSUE TITLE
Upgrade scaffolding to v0.4.6

### ISSUE THREAD

**Issue by sabre1041** [sigstore/helm-charts#291]
Upgrade of Helm charts to account for [v0.4.6 release](https://github.com/sigstore/scaffolding/releases/tag/v0.4.6) of scaffolding

* Alignment of configurations
* Introduction of new Tuf chart

**Comment by sabre1041** [comment]
This item is in progress and will include changes across almost every chart

**Comment by k4leung4** [comment]
this is done.
