### ISSUE TITLE
Use redis and mysql helm chart as dependencies

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/helm-charts#3]
Rekor helm chart would become lighter and easier to maintain if you can use helm chart dependencies for redis and mysql.

Is there any reason why redis and mysql are baked into the rekor chart ? Perhaps there is any specific configuration for those dependencies, as I saw you are not using the bitnami charts.

**Comment by sabre1041** [comment]
@hectorj2f The management of the dependent components was put under consideration. The initial goal was to replicate the functionality in the existing Docker Compose based deployment. With regard to chart dependencies, there were two avenues:

* Create separate dependency charts in this repository
* Make use of existing charts in the community
    * The bitnami charts are certainly well known and respected. Should a dependency be made from sigstore to the bitnami repository and the content?

To make an initial version available, an all in one chart was used. However, certainly interested in the thoughts of the community on the composition of these charts

**Comment by hectorj2f** [comment]
> The bitnami charts are certainly well known and respected. Should a dependency be made from sigstore to the bitnami repository and the content?

@sabre1041 Yes. I'll advocate for using the bitnami repository for both charts. Originally they were maintained by the community in the past, but they are now maintained under the bitnami repo which is a trustable source.

> To make an initial version available, an all in one chart was used. However, certainly interested in the thoughts of the community on the composition of these charts

The idea is to use these trusted helm repositories and use helm dependencies which would help maintaining and having an up-to-date chart. 

I could help with this migration to simplify the rekor chart.
