### ISSUE TITLE
Policy-controller helm chart suggest using deprecated secretKeyRef

### ISSUE THREAD

**Issue by maxking** [sigstore/helm-charts#310]
**Description**

According to the latest policy-controller docs, the usage of `cosign.secretKeyRef.name` is deprecated and people should be using `ClusterImagePolicy`. However the [current installation documentation](https://github.com/sigstore/helm-charts/tree/main/charts/policy-controller) still points to the old way to do this.

Since it is the only available public docs for installing policy-controller, it should reflect the latest recommendation to use `ClusterImagePolicy`.

**Version**

Latest

**Comment by hectorj2f** [comment]
@maxking Good point! Let's add it here too.

**Comment by sabre1041** [comment]
@hectorj2f @maxking is this still outstanding or can this issue be closed?

**Comment by hectorj2f** [comment]
Closing it!
