### ISSUE TITLE
policy-controller: namespace for webhook hardcoded in CRD

### ISSUE THREAD

**Issue by wojciechka** [sigstore/helm-charts#311]
**Description**

The namespace name is hardcoded to `cosign-system` rather than `{{ .Release.Namespace }}` in the CRD's conversion definition.

Because of that, deploying to a namespace different than `cosign-system` causes `kubectl get clusterimagepolicy` to fail with:

```
Error from server: conversion webhook for policy.sigstore.dev/v1alpha1, Kind=ClusterImagePolicy failed: Post "https://policy-webhook.cosign-system.svc:443/resource-conversion?timeout=30s": service "policy-webhook" not found
```

Affected file:

https://github.com/sigstore/helm-charts/blob/34df6521bf930398606438dcdc4852d54ecb78a8/charts/policy-controller/templates/crds/clusterimagepolicy.yaml#L25

**Version**

Chart version 0.2.3
Application version 0.3.0

**Comment by hectorj2f** [comment]
Good catch @wojciechka! Do you think you could create a PR to make that namespace configurable based on the Release.namespace ?

**Comment by wojciechka** [comment]
Yes, started by creating issues, but I want to add PRs for this and #312

**Comment by wojciechka** [comment]
> Good catch @wojciechka! Do you think you could create a PR to make that namespace configurable based on the Release.namespace ?

Potentially a silly question, does every commit require bumping the chart version and releasing it?

I'm fine doing it, but just want to check if there's a simpler way to include multiple changes in one release without putting both in a single PR.

**Comment by hectorj2f** [comment]
Yes, you just need to bump the chart version for this issue. The release is handled by our pipeline.
