### ISSUE TITLE
policy-controller-webhook failed to start

### ISSUE THREAD

**Issue by sorryforyou** [sigstore/helm-charts#393]
I installed "policy controller policy webhook" and "policy controller webhook" according to the steps you provided, but the installation of "policy controller webhook" failed. The probe indicates that the container is not started. I don't know why.

The log displays the following information：
Readiness probe failed: Get "https://10.244.1.25:8443/readyz": dial tcp 10.244.1.25:8443: connect: connection refused
Liveness probe failed: Get "https://10.244.1.25:8443/healthz": dial tcp 10.244.1.25:8443: connect: connection refused
Back-off restarting failed container

{"level":"info","ts":1666877997.4760294,"logger":"fallback","caller":"webhook/main.go:87","msg":"Initializing TUF root from  => https://sigstore-tuf-root.storage.googleapis.com"}
{"level":"panic","ts":1666878048.0219798,"logger":"fallback","caller":"webhook/main.go:89","msg":"Failed to initialize TUF client from  : updating local metadata and targets: error updating to TUF remote mirror: tuf: failed to download 3.root.json: Get \"https://sigstore-tuf-root.storage.googleapis.com/3.root.json\": net/http: TLS handshake timeout\nremote status:{\n\t\"mirror\": \"https://sigstore-tuf-root.storage.googleapis.com\",\n\t\"metadata\": {}\n}","stacktrace":"main.main\n\tgithub.com/sigstore/policy-controller/cmd/webhook/main.go:89\nruntime.main\n\truntime/proc.go:250"}
panic: Failed to initialize TUF client from  : updating local metadata and targets: error updating to TUF remote mirror: tuf: failed to download 3.root.json: Get "https://sigstore-tuf-root.storage.googleapis.com/3.root.json": net/http: TLS handshake timeout
remote status:{
	"mirror": "https://sigstore-tuf-root.storage.googleapis.com",
	"metadata": {}
}

goroutine 1 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x402d500?, {0x0?, 0x0?, 0xc0009d59e0?})
	go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0009dcb60, {0x0, 0x0, 0x0})
	go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*SugaredLogger).log(0xc0003b93c8, 0x4, {0x26e6057?, 0x0?}, {0xc000a51e60?, 0x2?, 0x2?}, {0x0, 0x0, 0x0})
	go.uber.org/zap@v1.23.0/sugar.go:287 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	go.uber.org/zap@v1.23.0/sugar.go:181
main.main()
	github.com/sigstore/policy-controller/cmd/webhook/main.go:89 +0x577

**Comment by hectorj2f** [comment]
related to: https://github.com/sigstore/policy-controller/pull/355

**Comment by hectorj2f** [comment]
Closing this issue! It has been fixed in v0.4.2. We are releasing a new version https://github.com/sigstore/helm-charts/pull/405.
