### ISSUE TITLE
Missing config for volumes and volumeMounts on policy-controller webhook deployment

### ISSUE THREAD

**Issue by xanderjjj** [sigstore/helm-charts#396]
**Description**

Being able to specify custom volumes and volumeMounts in the policy-controller webhook deployment will allow for adding custom CA certificates. This is required for situations where a tuf-mirror is only available through a repo mirror such as Artifactory with a custom CA certificate.

**Comment by hectorj2f** [comment]
@xanderjjj Just to confirm the requested functionality: do you want to add additional volumes or replace the existing ones https://github.com/sigstore/helm-charts/blob/main/charts/policy-controller/templates/webhook/deployment_webhook.yaml#L113 ?

**Comment by xanderjjj** [comment]
@hectorj2f I was thinking just additional volumes like in PR #399

**Comment by hectorj2f** [comment]
Sure, we can add that option.
