### ISSUE TITLE
Option to set `no-match-policy` in helm chart

### ISSUE THREAD

**Issue by akorp** [sigstore/helm-charts#407]
**Description**

Currently it is not possible to set `no-match-policy` in helm chart. It is possible to edit `no-match-policy` in `config-policy-controller` ConfigMap, but this requires  update of a resource (ConfigMap), which was created and managed by helm `app.kubernetes.io/managed-by: Helm`. This can potentially lead to conflicts. In our case it is also hard to implement since we use Terraform to deploy helm chart and to manage a resource created by Helm, it have to be first manually imported into Terraform state (and we want to avoid any manual config or post- helm install steps).

**Comment by hectorj2f** [comment]
Good catch @akorp! Let me fix that.

**Comment by akorp** [comment]
@hectorj2f tested and it look good!
Amazing how fast it went from a suggestion to a PR 🙌
