### ISSUE TITLE
consider providing Helm Chart Provenance and Integrity

### ISSUE THREAD

**Issue by developer-guy** [sigstore/helm-charts#45]
**Description**

We can use sigstore's helm-sigstore plugin, or GPG key to sign/verify Helm Chart, wouldn't be nice if we support that?

* https://github.com/sigstore/helm-sigstore
* https://helm.sh/docs/topics/provenance/

**Comment by sabre1041** [comment]
@developer-guy Work is actually in flight as we speak to implement this. Expect some output by end of the weekend

**Comment by developer-guy** [comment]
thanks 🙋🏻‍♂️
