### ISSUE TITLE
rekor treeid must be specified

### ISSUE THREAD

**Issue by raffaelespazzoli** [sigstore/helm-charts#468]
**Description**

Docs should explain that the rekor treeID must be specified and it's a numeric that must be written as a string.
Failing to specify it causes the pod not to be able to start as it does not find the configmap entry needed for an environment variable.
Scaffold could supply a default value here.

**Comment by sabre1041** [comment]
@raffaelespazzoli the Trillian Tree is created by the [createtree](https://github.com/sigstore/helm-charts/blob/main/charts/ctlog/templates/createtree-job.yaml) job and is not required to be specified

**Comment by abdennour** [comment]
are u saying ctlog chart become another dependency to rekor chart ? @sabre1041

**Comment by vipulagarwal** [comment]
createtree job is a part of sigtstore scaffolding and it is apart of rekor. We do not need ctlog as rekor dependency.
