### ISSUE TITLE
switch to Chainguard's netcat image 

### ISSUE THREAD

**Issue by tuananh** [sigstore/helm-charts#500]
**Description**

CG's netcat is multi-arch (amd64 and arm64) so we can remove nodeSelector

https://github.com/sigstore/helm-charts/blob/main/charts/trillian/values.yaml#L138

https://github.com/chainguard-images/images/tree/main/images/netcat

**Comment by flxw** [comment]
I'm not very deep into this area yet, but I'd be happy to collaborate on a PR with you. What do you think?

**Comment by tuananh** [comment]
the `nc` image from Chainguard is lacking `sh`

we use `sh` and `nc` in initContainer 

https://github.com/sigstore/helm-charts/blob/55e320ec47fea672bc0ad2472c73f56f4c1f0684/charts/trillian/templates/trillian-log-server/deployment.yaml#L43

so I think we need to open a PR to Chainguard's images repo first https://github.com/chainguard-images/images/blob/main/images/netcat/configs/latest.apko.yaml
