### ISSUE TITLE
Could not install policy controller in disable-tuf mode

### ISSUE THREAD

**Issue by Mukuls77** [sigstore/helm-charts#528]
**Question**
Hi i wanted to deploy policy controller in disabling TUF mode. so i used the following helm command to install the policy controller.

/home/mukul>helm install policy-controller -n cosign-system --set extraArgs.disable-tuf=true sigstore/policy-controller --devel

but still after passing the disable-tuf as true in extra Args the policy controller process are not coming up as they are still trying to connect the public sigstore tuf.

Kindly update what is the correct way to install policy-controller with disabling tuf.

policy-controller-policy-webhook-5985d96f75-m6z2m   1/1     Running   1 (4m58s ago)   9m21s
policy-controller-webhook-69dc7d6b4b-4wh84          0/1     Running   2 (2m17s ago)   9m21s

/home/mukul/Desktop>kubectl logs -n cosign-system policy-controller-webhook-69dc7d6b4b-4wh84
{"level":"info","ts":1683623042.9509282,"logger":"fallback","caller":"webhook/main.go:94","msg":"Initializing TUF root from  => https://sigstore-tuf-root.storage.googleapis.com/"}
{"level":"panic","ts":1683623076.5629852,"logger":"fallback","caller":"webhook/main.go:96","msg":"Failed to initialize TUF client from  : updating local metadata and targets: error updating to TUF remote mirror: tuf: failed to download 8.root.json: Get \"[https://sigstore-tuf-root.storage.googleapis.com/8.root.json\](https://sigstore-tuf-root.storage.googleapis.com/8.root.json%5C)": dial tcp [142.250.194.16:443](http://142.250.194.16:443/): i/o timeout\nremote status:

**Comment by hectorj2f** [comment]
@Mukuls77 Please, use `--set webhook.extraArgs.disable-tuf=true` instead the set argument wasn't valid in your comment.

**Comment by hectorj2f** [comment]
Closing this issue, as confirmed by the user!
