### ISSUE TITLE
Cosigned Helm Chart Docs Improperly Use Label/Annotation Interchangeably

### ISSUE THREAD

**Issue by MarkVLK** [sigstore/helm-charts#53]
**Cosigned Helm Chart Docs Improperly Use Label/Annotation Interchangeably**

In [the docs](https://github.com/sigstore/helm-charts/tree/main/charts/cosigned#enabling-admission-control) the words "[annotation](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/)" and "[label](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)" are used interchangeably, but are two different constructs in Kubernetes.

From testing, it appears as though to enable the cosigned admission webhook, you need to add `cosigned.sigstore.dev/include: "true"` as a label, not as an annotation.

**Comment by hectorj2f** [comment]
@MarkVLK You are right. @MarkVLK could you open a PR ?
