### ISSUE TITLE
Convert to shared charts: mysql, redis, trillian-log-server, trillian-log-signer

### ISSUE THREAD

**Issue by jdolitsky** [sigstore/helm-charts#58]
Let's extract the templates under the rekor chart into their own charts, so that we can just include them as dependencies for both rekor and fulcio

cc @sabre1041

**Comment by cpanato** [comment]
agree +1

**Comment by sabre1041** [comment]
@hydeenoble the initial component breakup has occurred. full release should be completed today.

**Comment by hydeenoble** [comment]
Oh. nice. Thanks for your response @sabre1041

**Comment by sabre1041** [comment]
Closing issue as solution has been implemented
