### ISSUE TITLE
CT Log to support AWS KMS

### ISSUE THREAD

**Issue by ChevronTango** [sigstore/helm-charts#583]
Right now it seems like CT Log is the only component that doesn't support AWS KMS, meaning it has to generate a cert and place it in a secret within the ctlog-system namespace. My current setup is reliant on KMS for everything except this one component. With Rekor recently adding support for AWS KMS, could CT Log also support it? Using the generated cert is undesirable for us in production.

Apologies if there is a better repo to raise this issue on. I was unable to find where CT Log is mastered.

**Comment by haydentherapper** [comment]
Sigstore doesn’t maintain the library. You can file an issue in https://github.com/google/certificate-transparency-go. The service currently does not support KMS keys, only keys loaded from disk, I assume for performance.

**Comment by ChevronTango** [comment]
Thanks @haydentherapper. I'll raise the issue there.
