### ISSUE TITLE
scaffold chart default values need to be updated to fix tuf secrets names mismatch

### ISSUE THREAD

**Issue by federico-falconieri-form3** [sigstore/helm-charts#678]
**Description**

* https://github.com/sigstore/helm-charts/pull/673/files correctly fixed https://github.com/sigstore/scaffolding/issues/873 and resulted in release of tuf chart `0.1.9`
* https://github.com/sigstore/helm-charts/commit/ae23b8e187834d5e1ed197612601f7075849aeab updated the scaffold chart to use the tuf chart at version `0.1.9`
* however the [default values for the tuf secrets names](https://github.com/sigstore/helm-charts/blob/5deb0541e41e001d3c2c8e11baea188cee5cbc01/charts/scaffold/values.yaml#L73-L82) are still the old wrong ones

scaffold `values.yaml` should also be updated to use the correct secret names. I think a temporary workaround is to [set your own secrets block as suggested here](https://github.com/sigstore/scaffolding/issues/873#issuecomment-1834042697) (I'm going to test this now. If it works I'll open a PR)

CC @sabre1041 

**Version**

scaffold 0.6.38

**Comment by federico-falconieri-form3** [comment]
I've tested that the suggested fix works, I will open a PR

**Comment by falcorocks** [comment]
PR: https://github.com/sigstore/helm-charts/pull/679
